### PR TITLE
small small / cosmetic fixes, drop py26

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
also i wanted to see whether the tests on travis-ci are actually working.

### CODE REVIEW

**Comment by liuliqiang** [comment]
seems good, would you mind combine commits into one?

**Comment by ThomasWaldmann** [comment]
Well, I could, but why should I?

Each commit has a specific topic and one usually should not mix topics as well as one should not mix functional changes ("real changes") with cosmetic changes (like whitespace changes).

**Comment by liuliqiang** [comment]
I think the only purpose for this patch is only for document changes。

**Comment by ThomasWaldmann** [comment]
If you insist on having it all in one commit, you can choose "squash" when merging this on the github web ui.

I still think separate commits are more appropriate.

**Comment by ThomasWaldmann** [comment]
so, what are you doing?

it seems like you picked some of my changes, so that this PR now has conflicts.

otoh, you missed to pick some essential stuff, like:
- fixing the inconsistency of supporting python older than 2.6 while not announcing support for older than 2.6 nor testing on older than 2.6
- fixing the type error for `tests_require` - it should be a list of str (list of package names, as you see for `install_requires`), not just str.

thanks for releasing at least something that can be use for python3.

**Comment by liuliqiang** [comment]
I fixed travis ci error in last saturday, and found out Python Meta error and fix it.

It's a misleading that some same code with your patch.

I have resolve the conflict and merge it now.

**Pull request merged**
